---
- name: copy setupHost.sh
  copy: src=../files/setupHost.sh dest=/tmp/ owner=root group=docker mode=0700

- name: define rabbitmq_clu_nodes.json
  shell: echo "{{hostvars[inventory_hostname]['rabbitmqCluNodes']}}" > /tmp/rabbitmq_clu_nodes.json

- name: reformat rabbitmq_clu_nodes.json
  shell: sed -i "s#'#\"#g" /tmp/rabbitmq_clu_nodes.json

- name: set cluster hostname in container
  shell: /tmp/setupHost.sh

- name: copy connect.sh
  copy: src=../files/connect.sh dest=/tmp/ owner=root group=docker mode=0700
  when: not hostvars[inventory_hostname]['rabbitmqCluPrimaryNode'] == hostvars[inventory_hostname]['rbmqNodeName']

- name: define rabbitmq_clu_name.json
  shell: echo "{{hostvars[inventory_hostname]['rabbitmqCluName']}}" > /tmp/rabbitmq_clu_name.json
  when: not hostvars[inventory_hostname]['rabbitmqCluPrimaryNode'] == hostvars[inventory_hostname]['rbmqNodeName']

- name: reformat rabbitmq_clu_nodes.json
  shell: sed -i "s#'#\"#g" /tmp/rabbitmq_clu_name.json
  when: not hostvars[inventory_hostname]['rabbitmqCluPrimaryNode'] == hostvars[inventory_hostname]['rbmqNodeName']

- name: connect node to primary cluster node
  shell: /tmp/connect.sh
  when: not hostvars[inventory_hostname]['rabbitmqCluPrimaryNode'] == hostvars[inventory_hostname]['rbmqNodeName']

- name: clean
  shell: rm /tmp/*.sh /tmp/*.json
