---
- name: ensure git is at the latest version
  yum: name=git state=latest
  when: provisioning

- name: add sslVerify=false
  command: git config --global http.sslverify "false"
  when: provisioning

- name: add /ECHINOPSII/ansible directory
  command: mkdir -p /ECHINOPSII/ansible
  ignore_errors: yes
  when: provisioning

- name: clone net.echinopsii.docker.base
  git: repo=http://stash.echinopsii.net/scm/necii/docker.base.git dest=/ECHINOPSII/ansible/docker.base clone=yes update=yes
  when: provisioning

- name: chown /ECHINOPSII/ansible
  command: chown -R ansible.ansible /ECHINOPSII/ansible
  when: provisioning

- name: clean docker env
  command: /usr/bin/dockerKlean
  ignore_errors: yes

- name: remove fedora.21.systemd.tw.mo docker container
  docker:
   name: "{{hostvars[inventory_hostname]['nodeName']}}"
   image: echinopsii/fedora.21.systemd.tw.mo
   state: absent
  when: not provisioning

- name: clean docker env
  command: /usr/bin/dockerKlean
  ignore_errors: yes

- name: push mo.env
  template: src=mo.env dest=/mo.env mode="0755"
  when: provisioning

- name: remove mo.env
  shell: rm /mo.env
  when: not provisioning

- name: run fedora.21.systemd.tw.mo docker container
  docker: 
   name: "{{hostvars[inventory_hostname]['nodeName']}}"
   hostname: "{{hostvars[inventory_hostname]['nodeName'] + '.' + ansible_fqdn}}"
   privileged: yes
   volumes: 
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /mo.env:/mo.env
   image: echinopsii/fedora.21.systemd.tw.mo
  when: provisioning
