---
- name: ensure git is at the latest version (yum)
  yum: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'yum' and docker_provisioning)

- name: ensure git is at the latest version (apt)
  apt: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'apt' and docker_provisioning)  

- name: add sslVerify=false
  command: git config --global http.sslverify "false"
  when: (provisioning and docker_provisioning)

- name: add /ECHINOPSII/ansible directory
  command: mkdir -p /ECHINOPSII/ansible
  ignore_errors: yes
  when: (provisioning and docker_provisioning)

- name: clone net.echinopsii.docker.base
  git: repo=http://stash.echinopsii.net/scm/necii/docker.base.git dest=/ECHINOPSII/ansible/docker.base clone=yes update=yes
  when: (provisioning and docker_provisioning)

- name: chown /ECHINOPSII/ansible
  command: chown -R ansible.ansible /ECHINOPSII/ansible
  when: (provisioning and docker_provisioning)

- name: remove fedora.21.systemd.tw.fd docker container
  docker:
   name: "{{hostvars[inventory_hostname]['fdNodeName']}}"
   image: echinopsii/fedora.21.systemd.tw.fd
   state: absent
  when: not provisioning

- name: push fd.env
  template: src=fd.env dest=/fd.env mode="0755"
  when: provisioning

- name: remove fd.env
  shell: rm /fd.env
  when: not provisioning

- name: run fedora.21.systemd.tw.fd docker container (not docker_overlay)
  docker: 
   name: "{{hostvars[inventory_hostname]['fdNodeName']}}"
   hostname: "{{hostvars[inventory_hostname]['fdNodeName'] + '.' + ansible_fqdn}}"
   privileged: yes
   volumes: 
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /fd.env:/fd.env
   image: echinopsii/fedora.21.systemd.tw.fd
  when: (provisioning and not docker_overlay)

- name: run fedora.21.systemd.tw.fd docker container (docker_overlay)
  docker:
   name: "{{hostvars[inventory_hostname]['fdNodeName']}}"
   hostname: "{{hostvars[inventory_hostname]['fdNodeName'] + '.' + ansible_fqdn}}"
   privileged: yes
   net: "{{hostvars[inventory_hostname]['fdLocalSubnetName']}}"
   volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /fd.env:/fd.env
   image: echinopsii/fedora.21.systemd.tw.fd
  when: (provisioning and docker_overlay)

- name: clean docker env
  command: /usr/bin/dockerKlean
  ignore_errors: yes

