---
- name: ensure git is at the latest version (dnf)
  dnf: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'dnf' and docker_provisioning)

- name: ensure git is at the latest version (yum)
  yum: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'yum' and docker_provisioning)

- name: ensure git is at the latest version (apt)
  apt: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'apt' and docker_provisioning)  

- name: add sslVerify=false
  command: git config --global http.sslverify "false"
  when: (provisioning and docker_provisioning)

- name: add /ECHINOPSII/ansible directory
  command: mkdir -p /ECHINOPSII/ansible
  ignore_errors: yes
  when: (provisioning and docker_provisioning)

- name: clone net.echinopsii.docker.base
  git: repo=http://stash.echinopsii.net/scm/necii/docker.base.git dest=/ECHINOPSII/ansible/docker.base clone=yes update=yes
  when: (provisioning and docker_provisioning)

- name: chown /ECHINOPSII/ansible
  command: chown -R ansible.ansible /ECHINOPSII/ansible
  when: (provisioning and docker_provisioning)

- name: remove fedora.21.systemd.tw.fo docker container
  docker_container:
   name: "{{hostvars[inventory_hostname]['foNodeName']}}"
   image: echinopsii/fedora.21.systemd.tw.fo
   state: absent
  when: not provisioning

- name: push fo.env
  template: src=fo.env dest=/fo.env mode="0755"
  when: provisioning

- name: remove fo.env
  shell: rm /fo.env
  when: not provisioning

- name: run fedora.21.systemd.tw.fo docker container (not docker_overlay)
  docker_container: 
   name: "{{hostvars[inventory_hostname]['foNodeName']}}"
   hostname: "{{hostvars[inventory_hostname]['foNodeName'] + '.' + ansible_hostname  + '.' + ansible_dns['search'][0]}}"
   privileged: yes
   volumes: 
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /fo.env:/fo.env
   image: echinopsii/fedora.21.systemd.tw.fo
  when: (provisioning and not docker_overlay)

- name: run fedora.21.systemd.tw.fo docker container (docker_overlay)
  docker_container:
   name: "{{hostvars[inventory_hostname]['foNodeName']}}"
   hostname: "{{hostvars[inventory_hostname]['foNodeName'] + '.' + ansible_hostname  + '.' + ansible_dns['search'][0]}}"
   privileged: yes
   networks:
   - name: "{{hostvars[inventory_hostname]['foLocalSubnetName']}}"
   volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /fo.env:/fo.env
   image: echinopsii/fedora.21.systemd.tw.fo
  when: (provisioning and docker_overlay)

- name: clean docker env
  command: /usr/bin/dockerKlean
  ignore_errors: yes

