---
- name: ensure git is at the latest version (dnf)
  dnf: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'dnf' and docker_provisioning)

- name: ensure git is at the latest version (yum)
  yum: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'yum' and docker_provisioning)

- name: ensure git is at the latest version (apt)
  apt: name=git state=latest
  when: (provisioning and ansible_pkg_mgr == 'apt' and docker_provisioning)  

- name: add sslVerify=false
  command: git config --global http.sslverify "false"
  when: (provisioning and docker_provisioning)

- name: add /ECHINOPSII/ansible directory
  command: mkdir -p /ECHINOPSII/ansible
  ignore_errors: yes
  when: (provisioning and docker_provisioning)

- name: clone net.echinopsii.docker.base
  git: repo=http://stash.echinopsii.net/scm/necii/docker.base.git dest=/ECHINOPSII/ansible/docker.base clone=yes update=yes
  when: (provisioning and docker_provisioning)

- name: chown /ECHINOPSII/ansible
  command: chown -R ansible.ansible /ECHINOPSII/ansible
  when: (provisioning and docker_provisioning)

- name: remove fedora.21.systemd.tw.bo docker container
  docker_container:
   name: "{{hostvars[inventory_hostname]['boNodeName']}}"
   image: echinopsii/fedora.21.systemd.tw.bo
   state: absent
  when: not provisioning

- name: push bo.env
  template: src=bo.env dest=/bo.env mode="0755"
  when: provisioning

- name: remove bo.env
  shell: rm /bo.env
  when: not provisioning

- name: run fedora.21.systemd.tw.bo docker container (no docker_overlay)
  docker_container: 
   name: "{{hostvars[inventory_hostname]['boNodeName']}}"
   hostname: "{{hostvars[inventory_hostname]['boNodeName'] + '.' + ansible_fqdn}}"
   privileged: yes
   volumes: 
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /bo.env:/bo.env
   image: echinopsii/fedora.21.systemd.tw.bo
  when: (provisioning and not docker_overlay)

- name: create fedora.21.systemd.tw.bo docker container (docker_overlay)
  command: docker create --name {{hostvars[inventory_hostname]['boNodeName']}} --hostname "{{hostvars[inventory_hostname]['boNodeName'] + '.' + ansible_fqdn}}" --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /bo.env:/bo.env --network={{hostvars[inventory_hostname]['cassOverlaySubnetName']}} echinopsii/fedora.21.systemd.tw.bo
  when: (provisioning and docker_overlay)

- name: connect bo container to local network
  command: docker network connect {{hostvars[inventory_hostname]['boLocalSubnetName']}} {{hostvars[inventory_hostname]['boNodeName']}}
  when: (provisioning and docker_overlay)

- name: start docker bo container
  command: docker start {{hostvars[inventory_hostname]['boNodeName']}}
  when: (provisioning and docker_overlay)

- name: clean docker env
  command: /usr/bin/dockerKlean
  ignore_errors: yes

